### ISSUE TITLE
How to create pre-processed data for a new dataset?

### ISSUE THREAD

**Issue by pawankmrs** [DeepLearnXMU/NSEG#3]
Could you share the script used for pre-processing the data for creating '.eg', '.lower' and 'vocab.pt' files?

**Comment by ARIES-LM** [comment]
Sorry for missing that. But the processing is simple:
1. Use a dependency parser to get POS and syntax
2. Select the word as entity if the POS is noun 
3. Find the nsubj and dobj to get the roles ( just use a POS tagger and ignore the roles if you think the dependency parser is time-consuming)

Use Vocab class in torchtext to get vocab.pt, Glove100 is enough.

**Comment by avinashsai** [comment]
Hi,
I have sentence in this order(example):
S1,S2,S3
S4,S1,S5

Can I use this algorithm to predict next sentence?? 
If I give a new sentence S6 how to predict next sentence??
