### ISSUE TITLE
Could you provide the Graph-SE version code? 

### ISSUE THREAD

**Issue by Stanxy** [DeepLearnXMU/NSEG#4]
Hi, recently we want to apply your model in a text ordering pipeline. But we found the code in the repo is a simplified version in the original paper called F-graph. Would you mind sharing us the Graph-SE version of code?

**Comment by ARIES-LM** [comment]
Hi, this is the code for Graph-SE. You can see the line 38 and 40 in seq2seq.py and there are two GRUs for sentence nodes and entity nodes.
